### ISSUE TITLE
На скриншоте программа с датой и температурой.

### ISSUE THREAD

**Issue by ingener555** [IllarionRUS/MH-Z19_CO2_Sensor_PC_Software#1]
Уважаемый Илларион.
Спасибо Вам за программу. Скажите пожалуйста, версия доступная для скачивания не имеет шкалу реального времени, есть просто посекундная шкала. Но на скриншоте по ссылке на документацию Ваша программа показывает временную шкалу и температуру датчика. Можно ли настроить отображение временной шкалы реального времени или скачать эту более функциональную версию Вашего произведения?

**Comment by IllarionRUS** [comment]
Приветствую! Вы из релиза взяли программу или из репозитория? Давно уже перепаял этот датчик к ардуино и не помню, возможно не коммитил последние изменения. В релизе должны быть последние правки, с температурой датчика и шкалой времени [ссылка](https://github.com/IllarionRUS/MH-Z19_CO2_Sensor_PC_Software/releases/download/1.1/MH-Z19_CO2_Sensor_PC_Software.zip)

**Comment by ingener555** [comment]
Скачивал из релиза, название архива MH-Z19_CO2_Sensor_PC_Software, из репозитория MH-Z19_CO2_Sensor_PC_Software-1.1, они без шкалы времени и температуры.
Скачал архив по Вашей ссылке, называется MH-Z19_CO2_Sensor_PC_Software, но там не запускается приложение совсем на Windows 10 64  :-(  Там содержимое папки Debug.
Посмотрите пожалуйста.

**Comment by ingener555** [comment]
Ваша версия ничем не отличается от версии первоисточника iliasam/MH-Z19_simple_pc_test. Не понимаю, зачем выкладывать скриншот с несуществующими возможностями. Или это планировалось в будущем?

**Comment by IllarionRUS** [comment]
В исходных кодах лежат два файла: старый, который взял как основу и мой новый. Новый - наверное не запускается из-за того что на ПК не установлен .Net Core 3.1.
Сейчас пере собрал две версии, одна включает в себя файлы этого Net Core а вторая предлагает скачать его.
Протестировал обе сборке на Windows Server 2008, где не установлен Net Core - обе сборки запустились.
![Run in Win2008 no install NET Core](https://user-images.githubusercontent.com/11155159/85917031-1dd31c80-b85f-11ea-97e8-5604268930d6.png)
![Run in Win2008](https://user-images.githubusercontent.com/11155159/85917032-1f9ce000-b85f-11ea-9205-1f8192712c9b.png)

[Ссылка на релиз](https://github.com/IllarionRUS/MH-Z19_CO2_Sensor_PC_Software/releases/tag/1.2)

**Comment by ingener555** [comment]
Уважаемый Илларион. Спасибо большое, все работает. Стольким людям помогли. Даже на международных торговых площадках ссылаются на Вашу программу.

**Comment by IllarionRUS** [comment]
Приятно что программа оказалась полезна не только мне.
